### ISSUE TITLE
Upgrade Firebase Version

### ISSUE THREAD

**Issue by TransmissionsDev** [donavon/use-firebase-auth#3]
Hey @donavon , this set of hooks is perfect for my use case, and I'd really like to use it, but the version of Firebase you are using uses an old version of grpc that won't compile on node versions above 10. Can you please update the version?

Thanks!

**Comment by darrenbutcher** [comment]
@TransmissionsDev Thanks for pointing this out (glossed over the fact that firebase was the culprit). Was having the same issue and had a lot of hair pulling as I was trying in integrate this with Gatsby. At first I couldn't even install the package (node v12.16.2) until I downgraded to node version 10. And even after I managed to do that I could not get Gatsby to build.

**THE FIX (using yarn):**
Since the maintainer doesn't seem active at the moment to bump the firebase dependency version, you can use yarn resolutions as a workaround.
https://stackoverflow.com/questions/40226639/how-do-i-override-nested-dependencies-with-yarn/41082766#41082766

package.json
```
"resolutions": {
   "firebase": "^7.14.2"
 }
```

Hope this helps anyone else that bumps into this.

**Comment by TransmissionsDev** [comment]
@darrenbutcher Thank you so much!

**Comment by ripern** [comment]
@donavon Would be great if you wanted to upgrade to later Firebase version and release a new version to npm.  :)
One of your forks did the upgrade here https://github.com/sorja/use-firebase-auth/commit/1647a3fad65c0728f072f7565d9c09b77c6eda5c. I could PR it if you prefer that.

**Comment by ripern** [comment]
PR: https://github.com/donavon/use-firebase-auth/pull/6
